/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RosterEntry = IDL.Record({
  'staffId' : IDL.Text,
  'date' : IDL.Text,
  'shiftTiming' : IDL.Text,
  'rosterId' : IDL.Text,
  'wardAssignment' : IDL.Text,
});
export const Document = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'staffId' : IDL.Text,
  'verificationId' : IDL.Text,
  'documentId' : IDL.Text,
  'issuedAt' : IDL.Int,
  'issuedBy' : IDL.Text,
});
export const StaffProfile = IDL.Record({
  'name' : IDL.Text,
  'designation' : IDL.Text,
  'role' : UserRole,
  'employeeId' : IDL.Text,
  'department' : IDL.Text,
});
export const LeaveStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const LeaveRequest = IDL.Record({
  'status' : LeaveStatus,
  'leaveId' : IDL.Text,
  'endDate' : IDL.Text,
  'staffId' : IDL.Text,
  'submittedAt' : IDL.Int,
  'leaveType' : IDL.Text,
  'startDate' : IDL.Text,
  'reason' : IDL.Text,
});
export const NoticeCategory = IDL.Variant({
  'circular' : IDL.Null,
  'memo' : IDL.Null,
  'policy' : IDL.Null,
});
export const Notice = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishedAt' : IDL.Int,
  'publishedBy' : IDL.Text,
  'category' : NoticeCategory,
  'noticeId' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'employeeId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignShift' : IDL.Func([RosterEntry], [], []),
  'createDocument' : IDL.Func([Document], [], []),
  'createStaffProfile' : IDL.Func([StaffProfile], [], []),
  'deleteDocument' : IDL.Func([IDL.Text], [], []),
  'deleteLeaveRequest' : IDL.Func([IDL.Text], [], []),
  'deleteNotice' : IDL.Func([IDL.Text], [], []),
  'deleteRosterEntry' : IDL.Func([IDL.Text], [], []),
  'deleteStaffProfile' : IDL.Func([IDL.Text], [], []),
  'getAllDocuments' : IDL.Func([], [IDL.Vec(Document)], ['query']),
  'getAllLeaveRequests' : IDL.Func([], [IDL.Vec(LeaveRequest)], ['query']),
  'getAllNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
  'getAllRosters' : IDL.Func([], [IDL.Vec(RosterEntry)], ['query']),
  'getAllStaff' : IDL.Func([], [IDL.Vec(StaffProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDocument' : IDL.Func([IDL.Text], [IDL.Opt(Document)], ['query']),
  'getLeaveRequest' : IDL.Func([IDL.Text], [IDL.Opt(LeaveRequest)], ['query']),
  'getNotice' : IDL.Func([IDL.Text], [IDL.Opt(Notice)], ['query']),
  'getRosterEntry' : IDL.Func([IDL.Text], [IDL.Opt(RosterEntry)], ['query']),
  'getStaffDocuments' : IDL.Func([IDL.Text], [IDL.Vec(Document)], ['query']),
  'getStaffLeaveRequests' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LeaveRequest)],
      ['query'],
    ),
  'getStaffProfile' : IDL.Func([IDL.Text], [IDL.Opt(StaffProfile)], ['query']),
  'getStaffRosterEntries' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(RosterEntry)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'publishNotice' : IDL.Func([Notice], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitLeaveRequest' : IDL.Func([LeaveRequest], [], []),
  'updateLeaveStatus' : IDL.Func([IDL.Text, LeaveStatus], [], []),
  'updateNotice' : IDL.Func([Notice], [], []),
  'updateRosterEntry' : IDL.Func([RosterEntry], [], []),
  'updateStaffProfile' : IDL.Func([StaffProfile], [], []),
  'verifyDocument' : IDL.Func([IDL.Text], [IDL.Opt(Document)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RosterEntry = IDL.Record({
    'staffId' : IDL.Text,
    'date' : IDL.Text,
    'shiftTiming' : IDL.Text,
    'rosterId' : IDL.Text,
    'wardAssignment' : IDL.Text,
  });
  const Document = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'staffId' : IDL.Text,
    'verificationId' : IDL.Text,
    'documentId' : IDL.Text,
    'issuedAt' : IDL.Int,
    'issuedBy' : IDL.Text,
  });
  const StaffProfile = IDL.Record({
    'name' : IDL.Text,
    'designation' : IDL.Text,
    'role' : UserRole,
    'employeeId' : IDL.Text,
    'department' : IDL.Text,
  });
  const LeaveStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const LeaveRequest = IDL.Record({
    'status' : LeaveStatus,
    'leaveId' : IDL.Text,
    'endDate' : IDL.Text,
    'staffId' : IDL.Text,
    'submittedAt' : IDL.Int,
    'leaveType' : IDL.Text,
    'startDate' : IDL.Text,
    'reason' : IDL.Text,
  });
  const NoticeCategory = IDL.Variant({
    'circular' : IDL.Null,
    'memo' : IDL.Null,
    'policy' : IDL.Null,
  });
  const Notice = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishedAt' : IDL.Int,
    'publishedBy' : IDL.Text,
    'category' : NoticeCategory,
    'noticeId' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'employeeId' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignShift' : IDL.Func([RosterEntry], [], []),
    'createDocument' : IDL.Func([Document], [], []),
    'createStaffProfile' : IDL.Func([StaffProfile], [], []),
    'deleteDocument' : IDL.Func([IDL.Text], [], []),
    'deleteLeaveRequest' : IDL.Func([IDL.Text], [], []),
    'deleteNotice' : IDL.Func([IDL.Text], [], []),
    'deleteRosterEntry' : IDL.Func([IDL.Text], [], []),
    'deleteStaffProfile' : IDL.Func([IDL.Text], [], []),
    'getAllDocuments' : IDL.Func([], [IDL.Vec(Document)], ['query']),
    'getAllLeaveRequests' : IDL.Func([], [IDL.Vec(LeaveRequest)], ['query']),
    'getAllNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
    'getAllRosters' : IDL.Func([], [IDL.Vec(RosterEntry)], ['query']),
    'getAllStaff' : IDL.Func([], [IDL.Vec(StaffProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDocument' : IDL.Func([IDL.Text], [IDL.Opt(Document)], ['query']),
    'getLeaveRequest' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(LeaveRequest)],
        ['query'],
      ),
    'getNotice' : IDL.Func([IDL.Text], [IDL.Opt(Notice)], ['query']),
    'getRosterEntry' : IDL.Func([IDL.Text], [IDL.Opt(RosterEntry)], ['query']),
    'getStaffDocuments' : IDL.Func([IDL.Text], [IDL.Vec(Document)], ['query']),
    'getStaffLeaveRequests' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LeaveRequest)],
        ['query'],
      ),
    'getStaffProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(StaffProfile)],
        ['query'],
      ),
    'getStaffRosterEntries' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(RosterEntry)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'publishNotice' : IDL.Func([Notice], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitLeaveRequest' : IDL.Func([LeaveRequest], [], []),
    'updateLeaveStatus' : IDL.Func([IDL.Text, LeaveStatus], [], []),
    'updateNotice' : IDL.Func([Notice], [], []),
    'updateRosterEntry' : IDL.Func([RosterEntry], [], []),
    'updateStaffProfile' : IDL.Func([StaffProfile], [], []),
    'verifyDocument' : IDL.Func([IDL.Text], [IDL.Opt(Document)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };