/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Document {
  'title' : string,
  'content' : string,
  'staffId' : string,
  'verificationId' : string,
  'documentId' : string,
  'issuedAt' : bigint,
  'issuedBy' : string,
}
export interface LeaveRequest {
  'status' : LeaveStatus,
  'leaveId' : string,
  'endDate' : string,
  'staffId' : string,
  'submittedAt' : bigint,
  'leaveType' : string,
  'startDate' : string,
  'reason' : string,
}
export type LeaveStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Notice {
  'title' : string,
  'content' : string,
  'publishedAt' : bigint,
  'publishedBy' : string,
  'category' : NoticeCategory,
  'noticeId' : string,
}
export type NoticeCategory = { 'circular' : null } |
  { 'memo' : null } |
  { 'policy' : null };
export interface RosterEntry {
  'staffId' : string,
  'date' : string,
  'shiftTiming' : string,
  'rosterId' : string,
  'wardAssignment' : string,
}
export interface StaffProfile {
  'name' : string,
  'designation' : string,
  'role' : UserRole,
  'employeeId' : string,
  'department' : string,
}
export interface UserProfile { 'name' : string, 'employeeId' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignShift' : ActorMethod<[RosterEntry], undefined>,
  'createDocument' : ActorMethod<[Document], undefined>,
  'createStaffProfile' : ActorMethod<[StaffProfile], undefined>,
  'deleteDocument' : ActorMethod<[string], undefined>,
  'deleteLeaveRequest' : ActorMethod<[string], undefined>,
  'deleteNotice' : ActorMethod<[string], undefined>,
  'deleteRosterEntry' : ActorMethod<[string], undefined>,
  'deleteStaffProfile' : ActorMethod<[string], undefined>,
  'getAllDocuments' : ActorMethod<[], Array<Document>>,
  'getAllLeaveRequests' : ActorMethod<[], Array<LeaveRequest>>,
  'getAllNotices' : ActorMethod<[], Array<Notice>>,
  'getAllRosters' : ActorMethod<[], Array<RosterEntry>>,
  'getAllStaff' : ActorMethod<[], Array<StaffProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDocument' : ActorMethod<[string], [] | [Document]>,
  'getLeaveRequest' : ActorMethod<[string], [] | [LeaveRequest]>,
  'getNotice' : ActorMethod<[string], [] | [Notice]>,
  'getRosterEntry' : ActorMethod<[string], [] | [RosterEntry]>,
  'getStaffDocuments' : ActorMethod<[string], Array<Document>>,
  'getStaffLeaveRequests' : ActorMethod<[string], Array<LeaveRequest>>,
  'getStaffProfile' : ActorMethod<[string], [] | [StaffProfile]>,
  'getStaffRosterEntries' : ActorMethod<[string], Array<RosterEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'publishNotice' : ActorMethod<[Notice], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitLeaveRequest' : ActorMethod<[LeaveRequest], undefined>,
  'updateLeaveStatus' : ActorMethod<[string, LeaveStatus], undefined>,
  'updateNotice' : ActorMethod<[Notice], undefined>,
  'updateRosterEntry' : ActorMethod<[RosterEntry], undefined>,
  'updateStaffProfile' : ActorMethod<[StaffProfile], undefined>,
  'verifyDocument' : ActorMethod<[string], [] | [Document]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];