/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RosterEntry {
    staffId: string;
    date: string;
    shiftTiming: string;
    rosterId: string;
    wardAssignment: string;
}
export interface LeaveRequest {
    status: LeaveStatus;
    leaveId: string;
    endDate: string;
    staffId: string;
    submittedAt: bigint;
    leaveType: string;
    startDate: string;
    reason: string;
}
export interface Document {
    title: string;
    content: string;
    staffId: string;
    verificationId: string;
    documentId: string;
    issuedAt: bigint;
    issuedBy: string;
}
export interface StaffProfile {
    name: string;
    designation: string;
    role: UserRole;
    employeeId: string;
    department: string;
}
export interface Notice {
    title: string;
    content: string;
    publishedAt: bigint;
    publishedBy: string;
    category: NoticeCategory;
    noticeId: string;
}
export interface UserProfile {
    name: string;
    employeeId: string;
}
export enum LeaveStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum NoticeCategory {
    circular = "circular",
    memo = "memo",
    policy = "policy"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignShift(entry: RosterEntry): Promise<void>;
    createDocument(document: Document): Promise<void>;
    createStaffProfile(profile: StaffProfile): Promise<void>;
    deleteDocument(documentId: string): Promise<void>;
    deleteLeaveRequest(leaveId: string): Promise<void>;
    deleteNotice(noticeId: string): Promise<void>;
    deleteRosterEntry(rosterId: string): Promise<void>;
    deleteStaffProfile(employeeId: string): Promise<void>;
    getAllDocuments(): Promise<Array<Document>>;
    getAllLeaveRequests(): Promise<Array<LeaveRequest>>;
    getAllNotices(): Promise<Array<Notice>>;
    getAllRosters(): Promise<Array<RosterEntry>>;
    getAllStaff(): Promise<Array<StaffProfile>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDocument(documentId: string): Promise<Document | null>;
    getLeaveRequest(leaveId: string): Promise<LeaveRequest | null>;
    getNotice(noticeId: string): Promise<Notice | null>;
    getRosterEntry(rosterId: string): Promise<RosterEntry | null>;
    getStaffDocuments(staffId: string): Promise<Array<Document>>;
    getStaffLeaveRequests(staffId: string): Promise<Array<LeaveRequest>>;
    getStaffProfile(employeeId: string): Promise<StaffProfile | null>;
    getStaffRosterEntries(staffId: string): Promise<Array<RosterEntry>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    publishNotice(notice: Notice): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitLeaveRequest(request: LeaveRequest): Promise<void>;
    updateLeaveStatus(leaveId: string, status: LeaveStatus): Promise<void>;
    updateNotice(notice: Notice): Promise<void>;
    updateRosterEntry(entry: RosterEntry): Promise<void>;
    updateStaffProfile(profile: StaffProfile): Promise<void>;
    verifyDocument(verificationId: string): Promise<Document | null>;
}
import type { Document as _Document, LeaveRequest as _LeaveRequest, LeaveStatus as _LeaveStatus, Notice as _Notice, NoticeCategory as _NoticeCategory, RosterEntry as _RosterEntry, StaffProfile as _StaffProfile, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignShift(arg0: RosterEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignShift(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignShift(arg0);
            return result;
        }
    }
    async createDocument(arg0: Document): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createDocument(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDocument(arg0);
            return result;
        }
    }
    async createStaffProfile(arg0: StaffProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createStaffProfile(to_candid_StaffProfile_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStaffProfile(to_candid_StaffProfile_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteDocument(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDocument(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDocument(arg0);
            return result;
        }
    }
    async deleteLeaveRequest(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLeaveRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLeaveRequest(arg0);
            return result;
        }
    }
    async deleteNotice(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNotice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNotice(arg0);
            return result;
        }
    }
    async deleteRosterEntry(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRosterEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRosterEntry(arg0);
            return result;
        }
    }
    async deleteStaffProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStaffProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStaffProfile(arg0);
            return result;
        }
    }
    async getAllDocuments(): Promise<Array<Document>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDocuments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDocuments();
            return result;
        }
    }
    async getAllLeaveRequests(): Promise<Array<LeaveRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLeaveRequests();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLeaveRequests();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNotices(): Promise<Array<Notice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNotices();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNotices();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRosters(): Promise<Array<RosterEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRosters();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRosters();
            return result;
        }
    }
    async getAllStaff(): Promise<Array<StaffProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStaff();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStaff();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDocument(arg0: string): Promise<Document | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocument(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocument(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaveRequest(arg0: string): Promise<LeaveRequest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaveRequest(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaveRequest(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotice(arg0: string): Promise<Notice | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotice(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotice(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRosterEntry(arg0: string): Promise<RosterEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRosterEntry(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRosterEntry(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStaffDocuments(arg0: string): Promise<Array<Document>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStaffDocuments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStaffDocuments(arg0);
            return result;
        }
    }
    async getStaffLeaveRequests(arg0: string): Promise<Array<LeaveRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStaffLeaveRequests(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStaffLeaveRequests(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStaffProfile(arg0: string): Promise<StaffProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStaffProfile(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStaffProfile(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStaffRosterEntries(arg0: string): Promise<Array<RosterEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStaffRosterEntries(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStaffRosterEntries(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async publishNotice(arg0: Notice): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.publishNotice(to_candid_Notice_n26(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishNotice(to_candid_Notice_n26(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitLeaveRequest(arg0: LeaveRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitLeaveRequest(to_candid_LeaveRequest_n30(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitLeaveRequest(to_candid_LeaveRequest_n30(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateLeaveStatus(arg0: string, arg1: LeaveStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLeaveStatus(arg0, to_candid_LeaveStatus_n32(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLeaveStatus(arg0, to_candid_LeaveStatus_n32(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateNotice(arg0: Notice): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNotice(to_candid_Notice_n26(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNotice(to_candid_Notice_n26(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateRosterEntry(arg0: RosterEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRosterEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRosterEntry(arg0);
            return result;
        }
    }
    async updateStaffProfile(arg0: StaffProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStaffProfile(to_candid_StaffProfile_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStaffProfile(to_candid_StaffProfile_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async verifyDocument(arg0: string): Promise<Document | null> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyDocument(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyDocument(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_LeaveRequest_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeaveRequest): LeaveRequest {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_LeaveStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeaveStatus): LeaveStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_NoticeCategory_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NoticeCategory): NoticeCategory {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Notice_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notice): Notice {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_StaffProfile_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StaffProfile): StaffProfile {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Document]): Document | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LeaveRequest]): LeaveRequest | null {
    return value.length === 0 ? null : from_candid_LeaveRequest_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Notice]): Notice | null {
    return value.length === 0 ? null : from_candid_Notice_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RosterEntry]): RosterEntry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StaffProfile]): StaffProfile | null {
    return value.length === 0 ? null : from_candid_StaffProfile_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    content: string;
    publishedAt: bigint;
    publishedBy: string;
    category: _NoticeCategory;
    noticeId: string;
}): {
    title: string;
    content: string;
    publishedAt: bigint;
    publishedBy: string;
    category: NoticeCategory;
    noticeId: string;
} {
    return {
        title: value.title,
        content: value.content,
        publishedAt: value.publishedAt,
        publishedBy: value.publishedBy,
        category: from_candid_NoticeCategory_n13(_uploadFile, _downloadFile, value.category),
        noticeId: value.noticeId
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    designation: string;
    role: _UserRole;
    employeeId: string;
    department: string;
}): {
    name: string;
    designation: string;
    role: UserRole;
    employeeId: string;
    department: string;
} {
    return {
        name: value.name,
        designation: value.designation,
        role: from_candid_UserRole_n18(_uploadFile, _downloadFile, value.role),
        employeeId: value.employeeId,
        department: value.department
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _LeaveStatus;
    leaveId: string;
    endDate: string;
    staffId: string;
    submittedAt: bigint;
    leaveType: string;
    startDate: string;
    reason: string;
}): {
    status: LeaveStatus;
    leaveId: string;
    endDate: string;
    staffId: string;
    submittedAt: bigint;
    leaveType: string;
    startDate: string;
    reason: string;
} {
    return {
        status: from_candid_LeaveStatus_n8(_uploadFile, _downloadFile, value.status),
        leaveId: value.leaveId,
        endDate: value.endDate,
        staffId: value.staffId,
        submittedAt: value.submittedAt,
        leaveType: value.leaveType,
        startDate: value.startDate,
        reason: value.reason
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    circular: null;
} | {
    memo: null;
} | {
    policy: null;
}): NoticeCategory {
    return "circular" in value ? NoticeCategory.circular : "memo" in value ? NoticeCategory.memo : "policy" in value ? NoticeCategory.policy : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): LeaveStatus {
    return "pending" in value ? LeaveStatus.pending : "approved" in value ? LeaveStatus.approved : "rejected" in value ? LeaveStatus.rejected : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notice>): Array<Notice> {
    return value.map((x)=>from_candid_Notice_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StaffProfile>): Array<StaffProfile> {
    return value.map((x)=>from_candid_StaffProfile_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LeaveRequest>): Array<LeaveRequest> {
    return value.map((x)=>from_candid_LeaveRequest_n6(_uploadFile, _downloadFile, x));
}
function to_candid_LeaveRequest_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeaveRequest): _LeaveRequest {
    return to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_LeaveStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeaveStatus): _LeaveStatus {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_NoticeCategory_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NoticeCategory): _NoticeCategory {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_Notice_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Notice): _Notice {
    return to_candid_record_n27(_uploadFile, _downloadFile, value);
}
function to_candid_StaffProfile_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StaffProfile): _StaffProfile {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    content: string;
    publishedAt: bigint;
    publishedBy: string;
    category: NoticeCategory;
    noticeId: string;
}): {
    title: string;
    content: string;
    publishedAt: bigint;
    publishedBy: string;
    category: _NoticeCategory;
    noticeId: string;
} {
    return {
        title: value.title,
        content: value.content,
        publishedAt: value.publishedAt,
        publishedBy: value.publishedBy,
        category: to_candid_NoticeCategory_n28(_uploadFile, _downloadFile, value.category),
        noticeId: value.noticeId
    };
}
function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: LeaveStatus;
    leaveId: string;
    endDate: string;
    staffId: string;
    submittedAt: bigint;
    leaveType: string;
    startDate: string;
    reason: string;
}): {
    status: _LeaveStatus;
    leaveId: string;
    endDate: string;
    staffId: string;
    submittedAt: bigint;
    leaveType: string;
    startDate: string;
    reason: string;
} {
    return {
        status: to_candid_LeaveStatus_n32(_uploadFile, _downloadFile, value.status),
        leaveId: value.leaveId,
        endDate: value.endDate,
        staffId: value.staffId,
        submittedAt: value.submittedAt,
        leaveType: value.leaveType,
        startDate: value.startDate,
        reason: value.reason
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    designation: string;
    role: UserRole;
    employeeId: string;
    department: string;
}): {
    name: string;
    designation: string;
    role: _UserRole;
    employeeId: string;
    department: string;
} {
    return {
        name: value.name,
        designation: value.designation,
        role: to_candid_UserRole_n1(_uploadFile, _downloadFile, value.role),
        employeeId: value.employeeId,
        department: value.department
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NoticeCategory): {
    circular: null;
} | {
    memo: null;
} | {
    policy: null;
} {
    return value == NoticeCategory.circular ? {
        circular: null
    } : value == NoticeCategory.memo ? {
        memo: null
    } : value == NoticeCategory.policy ? {
        policy: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeaveStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == LeaveStatus.pending ? {
        pending: null
    } : value == LeaveStatus.approved ? {
        approved: null
    } : value == LeaveStatus.rejected ? {
        rejected: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
